# Generated by Django 4.0.3 on 2022-05-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=255, null=True)),
                ('profile', models.ImageField(default=None, upload_to='images/')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', models.CharField(default=None, max_length=255)),
                ('contact', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Administrators',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=255, null=True)),
                ('lastname', models.CharField(default=None, max_length=255)),
                ('profile', models.ImageField(default=None, upload_to='images/')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('contact', models.IntegerField(default=None)),
                ('day', models.IntegerField(choices=[(1, 'MONDAY'), (2, 'TUESDAY'), (3, 'WEDNESDAY'), (4, 'THURSDAY'), (5, 'FRIDAY'), (6, 'SATURDAY'), (7, 'SUNDAY')], default=None)),
                ('location', models.CharField(default=None, max_length=255)),
                ('truck_id', models.CharField(default=None, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(default=None, max_length=255, null=True)),
                ('number_plate', models.CharField(default=None, max_length=255)),
                ('details', models.TextField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Trucks',
            },
        ),
    ]
