# Generated by Django 4.0.3 on 2022-06-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrators',
            name='contact',
            field=models.TextField(default=None),
        ),
    ]
