# Generated by Django 4.0.3 on 2022-04-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_administrators_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='firstname',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='helpcenter',
            name='user_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pricings',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='user_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='driver_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
