# Generated by Django 4.0.3 on 2022-04-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_drivers_firstname_alter_helpcenter_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpCenter',
        ),
        migrations.DeleteModel(
            name='Pricings',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
