# Generated by Django 4.0.3 on 2022-04-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('mode', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('pricing', models.CharField(max_length=255)),
                ('day', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
                ('profile', models.ImageField(upload_to='images/')),
                ('contact', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
