# Generated by Django 4.0.3 on 2022-05-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='highlighted',
        ),
    ]
