# Generated by Django 4.0.3 on 2022-04-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_payments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='mode',
            field=models.CharField(choices=[(1, 'one time payment'), (2, 'subscription')], max_length=255),
        ),
    ]
