# Generated by Django 4.0.3 on 2022-04-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_users_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='mode',
            field=models.IntegerField(choices=[(1, 'one time payment'), (2, 'subscription')]),
        ),
    ]
