# Generated by Django 4.0.3 on 2022-04-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basemodel', '0002_alter_pricings_type_alter_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved')], default=None),
        ),
    ]
