# Generated by Django 4.0.3 on 2022-04-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basemodel', '0003_alter_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricings',
            name='type',
            field=models.IntegerField(choices=[(1, 'one time payment'), (2, 'subscription')], default=None),
        ),
    ]
